default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  database: agenda_edu_backend_development
  username: agenda_edu_backend
  password: password

test:
  <<: *default
  host: db
  database: agenda_edu_backend_test
  username: agenda_edu_backend
  password: password

production:
  <<: *default
  url: <%= ENV['DATABASE_URL_PRODUCTION'] %>